// src/data/posters.ts
//
// Smart poster data layer — uses pre-optimized WebP thumbnails + medium-res
// instead of raw 224MB PNGs. Generated by: node scripts/optimize-posters.mjs
//
// Grid uses tiny thumbnails (~20KB each, total ~0.7MB)
// Lightbox uses medium-res (~100KB each, total ~3.8MB)
// Blur placeholders are inlined base64 (~300B each) for instant skeleton

import manifest from "./posters-manifest.json";

export interface PosterItem {
  id: string;
  title: string;
  /** Optimized WebP thumbnail path (grid cell, ~400px) */
  thumb: string;
  /** Optimized WebP medium path (lightbox, ~1200px) */
  medium: string;
  /** Original image dimensions */
  width: number;
  height: number;
  /** Tiny base64 blur placeholder for instant loading */
  blurDataURL: string;
}

// Human-readable titles mapped by slug id
const titles: Record<string, string> = {
  "poster_-_s7metopen": "Poster Metopen S7",
  "poster_2": "Poster Exhibition 2",
  "iga4-fastupb": "Fast UPB IGA4",
  "be": "Design BE",
  "coverbuku": "Cover Buku Visual",
  "feed1": "Feed Design 1",
  "fposter": "Festival Poster",
  "highlight1": "Highlight Story 1",
  "iga4-maulidnabi": "Maulid Nabi IGA4",
  "iga4_logos3": "Logo Concept S3",
  "iga4_logos4": "Logo Concept S4",
  "jerseyfullbg": "Jersey Full BG",
  "jerseyfullwg": "Jersey Full WG",
  "kedaisultan": "Kedai Sultan Branding",
  "logo_s7_v2": "Logo S7 V2",
  "logo_webhook_2": "Webhook Identity",
  "mikelgilar": "Mikel Gilar Artwork",
  "mole": "Mole Graphic Design",
  "poster": "Main Poster",
  "posterbe": "Poster BE Showcase",
  "posterbogor2": "Poster Bogor Event",
  "postermbd2": "Poster MBD 2",
  "posterpcd1": "Poster PCD Part 1",
  "posterpcd2": "Poster PCD Part 2",
  "postersedotwc": "Poster Sedot WC Humor",
  "ppgithub2": "GitHub Profile Graphic",
  "rafidito": "Rafi Dito Visual",
  "rekapbogor2024": "Rekap Bogor 2024",
  "salinan_dari_blue_gradient_technology_poster_1": "Blue Gradient Tech Poster",
  "semua2": "Semua Visual 2",
  "spanduk_pangandaran23": "Spanduk Pangandaran 2023",
  "tmbpcd": "Thumbnail PCD",
  "tobearockandnottoroll": "To Be A Rock And Not To Roll",
  "ukmbolav1": "UKM Bola V1",
  "web2": "Web Creative 2",
  "wptadika2v2": "Wallpaper Tadika 2 V2",
  "artboard_2": "Artboard Creative 2",
};

export const posterImages: PosterItem[] = manifest.map((entry) => ({
  id: entry.id,
  title: titles[entry.id] || entry.originalFile.replace(/\.png$/i, ""),
  thumb: entry.thumb,
  medium: entry.medium,
  width: entry.width,
  height: entry.height,
  blurDataURL: entry.blurDataURL,
}));
